# Generated by Django 4.2.17 on 2025-05-30 12:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.organization'),
        ),
        migrations.AlterField(
            model_name='balancelog',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Сумма, на которую изменяется баланс', max_digits=15, verbose_name='Сумма изменения'),
        ),
        migrations.AlterField(
            model_name='balancelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата изменения баланса', verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='balancelog',
            name='new_balance',
            field=models.DecimalField(decimal_places=2, help_text='Новый баланс организации', max_digits=15, verbose_name='Новый баланс'),
        ),
        migrations.AlterField(
            model_name='balancelog',
            name='organization',
            field=models.ForeignKey(help_text='Организация, для которой изменяется баланс', on_delete=django.db.models.deletion.CASCADE, related_name='balance_logs', to='payments.organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='balancelog',
            name='payment',
            field=models.ForeignKey(blank=True, help_text='Платеж, который привел к изменению баланса', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.payment', verbose_name='Платеж'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Сумма на балансе организации', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='inn',
            field=models.CharField(help_text='ИНН организации', max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Сумма платежа', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата создания', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='document_date',
            field=models.DateTimeField(help_text='Дата документа', verbose_name='Дата документа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='document_number',
            field=models.CharField(help_text='Номер документа', max_length=50, verbose_name='Номер документа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payer_inn',
            field=models.CharField(help_text='ИНН плательщика', max_length=12, verbose_name='ИНН плательщика'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['inn'], name='payments_or_inn_edce24_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['operation_id'], name='payments_pa_operati_b6f284_idx'),
        ),
    ]
